spring.application.name=finances
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.writer-with-default-pretty-printer=true
spring.datasource.url=jdbc:mysql://localhost:3306/finance
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=G7@kL#2mQ!9x$R4v&N8p*Z1t^Y6d%H3?
jwt.expiration=86400000
spring.jackson.serialization.write-dates-as-timestamps=false

spring.data.web.pageable.one-indexed-parameters=false

spring.threads.virtual.enabled=true

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.whitelabel.enabled=false